# Generated by Django 3.0.5 on 2022-04-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
